# DigitalOcean App Platform Configuration
# Save this as .do/app.yaml in your repo for auto-deployment

name: snapmail-backend
services:
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/snapmail-backend
      branch: main
      deploy_on_push: true
    build_command: npm install
    run_command: npm start
    envs:
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_DOMAIN
        scope: RUN_TIME
        value: yournamespace.testmail.app
      - key: PORT
        scope: RUN_TIME
        value: "3001"
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
